// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/embed.dart';
import 'api/matrix.dart';
import 'api/matrix_trace.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1816865888;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_pin',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String?> crateApiMatrixAccountDataGet({
    required String role,
    required String name,
  });

  Future<void> crateApiMatrixAccountDataPut({
    required String role,
    required String name,
    required String value,
  });

  Future<bool> crateApiMatrixBackupExistsOnServer();

  Future<String> crateApiMatrixCreateSelfRoom();

  Future<String> crateApiMatrixDownloadMedia({
    required String roomId,
    required String eventId,
  });

  Future<E2eeStatus> crateApiMatrixE2EeStatus();

  Future<void> crateApiEmbedEmbedInit({
    required List<int> model,
    required String tokenizerJson,
  });

  bool crateApiEmbedEmbedReady();

  Future<Float32List> crateApiEmbedEmbedText({required String text});

  Future<String> crateApiMatrixEnableRecovery();

  Future<String> crateApiMatrixEnsureRecoveryFor({required String role});

  Future<String?> crateApiMatrixFetchEventContent({
    required String role,
    required String roomId,
    required String eventId,
  });

  Future<String?> crateApiMatrixGetDisplayName({required String role});

  Future<String> crateApiMatrixGetOrCreatePinDm({required String pinUid});

  Future<String?> crateApiMatrixGetPrefsState({required String roomId});

  Future<String?> crateApiMatrixGetState({
    required String role,
    required String roomId,
    required String eventType,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  bool crateApiMatrixIsLoggedIn();

  Future<void> crateApiMatrixJoinRoom({
    required String role,
    required String roomId,
  });

  Future<void> crateApiMatrixLeaveRoom({
    required String role,
    required String roomId,
  });

  Future<List<RoomSummary>> crateApiMatrixListRooms();

  Future<Session> crateApiMatrixLogin({
    required String role,
    required String homeserver,
    required String dbPath,
    required String username,
    required String password,
  });

  Future<Session> crateApiMatrixLoginToken({
    required String role,
    required String homeserver,
    required String dbPath,
    required String token,
  });

  Future<void> crateApiMatrixLogout({
    required String role,
    required String dbPath,
  });

  Future<void> crateApiMatrixRecoverWithKey({required String recoveryKey});

  Future<void> crateApiMatrixRecoverWithKeyFor({
    required String role,
    required String recoveryKey,
  });

  Future<String> crateApiMatrixRecoveryState();

  Future<String> crateApiMatrixResetRecovery({required String password});

  Future<String> crateApiMatrixResetRecoveryKey();

  Future<void> crateApiMatrixRestore({
    required String role,
    required String homeserver,
    required String dbPath,
    required String userId,
    required String deviceId,
    required String accessToken,
  });

  Future<bool> crateApiMatrixRoomInStore({required String roomId});

  Future<List<String>> crateApiMatrixRoomMembers({required String roomId});

  Future<TimelinePage> crateApiMatrixRoomMessages({
    required String role,
    required String roomId,
    String? from,
    required int limit,
  });

  Future<String?> crateApiMatrixSecretGet({
    required String role,
    required String recoveryKey,
    required String name,
  });

  Future<void> crateApiMatrixSecretPut({
    required String role,
    required String recoveryKey,
    required String name,
    required String value,
  });

  Future<String> crateApiMatrixSendAttachment({
    required String role,
    required String roomId,
    required String filename,
    required String mime,
    required List<int> bytes,
    String? caption,
  });

  Future<String> crateApiMatrixSendCustomEvent({
    required String role,
    required String roomId,
    required String eventType,
    required String contentJson,
  });

  Future<String> crateApiMatrixSendText({
    required String role,
    required String roomId,
    required String body,
    String? flexJson,
    String? metaJson,
  });

  Future<void> crateApiMatrixSetDisplayName({
    required String role,
    required String name,
  });

  Future<void> crateApiMatrixSetState({
    required String role,
    required String roomId,
    required String eventType,
    required String contentJson,
  });

  Future<String> crateApiMatrixSsoLoginUrl({
    required String homeserver,
    required String dbPath,
    required String redirectUrl,
    String? idpId,
  });

  Stream<String> crateApiMatrixTraceStartMatrixTrace();

  Stream<ChatMessage> crateApiMatrixStartSync();

  Future<void> crateApiMatrixStartSyncRole({required String role});

  Future<void> crateApiMatrixVerificationAccept({required String flowId});

  Future<void> crateApiMatrixVerificationCancel({required String flowId});

  Future<void> crateApiMatrixVerificationConfirm({required String flowId});

  Future<IncomingVerification?> crateApiMatrixVerificationPollIncoming();

  Future<String> crateApiMatrixVerificationRequestSelf();

  Future<VerificationTick> crateApiMatrixVerificationTick({
    required String flowId,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String?> crateApiMatrixAccountDataGet({
    required String role,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixAccountDataGetConstMeta,
        argValues: [role, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixAccountDataGetConstMeta =>
      const TaskConstMeta(
        debugName: "account_data_get",
        argNames: ["role", "name"],
      );

  @override
  Future<void> crateApiMatrixAccountDataPut({
    required String role,
    required String name,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixAccountDataPutConstMeta,
        argValues: [role, name, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixAccountDataPutConstMeta =>
      const TaskConstMeta(
        debugName: "account_data_put",
        argNames: ["role", "name", "value"],
      );

  @override
  Future<bool> crateApiMatrixBackupExistsOnServer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixBackupExistsOnServerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixBackupExistsOnServerConstMeta =>
      const TaskConstMeta(debugName: "backup_exists_on_server", argNames: []);

  @override
  Future<String> crateApiMatrixCreateSelfRoom() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixCreateSelfRoomConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixCreateSelfRoomConstMeta =>
      const TaskConstMeta(debugName: "create_self_room", argNames: []);

  @override
  Future<String> crateApiMatrixDownloadMedia({
    required String roomId,
    required String eventId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixDownloadMediaConstMeta,
        argValues: [roomId, eventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixDownloadMediaConstMeta =>
      const TaskConstMeta(
        debugName: "download_media",
        argNames: ["roomId", "eventId"],
      );

  @override
  Future<E2eeStatus> crateApiMatrixE2EeStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_e_2_ee_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixE2EeStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixE2EeStatusConstMeta =>
      const TaskConstMeta(debugName: "e2ee_status", argNames: []);

  @override
  Future<void> crateApiEmbedEmbedInit({
    required List<int> model,
    required String tokenizerJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(model, serializer);
          sse_encode_String(tokenizerJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbedEmbedInitConstMeta,
        argValues: [model, tokenizerJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedEmbedInitConstMeta => const TaskConstMeta(
    debugName: "embed_init",
    argNames: ["model", "tokenizerJson"],
  );

  @override
  bool crateApiEmbedEmbedReady() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEmbedEmbedReadyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedEmbedReadyConstMeta =>
      const TaskConstMeta(debugName: "embed_ready", argNames: []);

  @override
  Future<Float32List> crateApiEmbedEmbedText({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEmbedEmbedTextConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEmbedEmbedTextConstMeta =>
      const TaskConstMeta(debugName: "embed_text", argNames: ["text"]);

  @override
  Future<String> crateApiMatrixEnableRecovery() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixEnableRecoveryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixEnableRecoveryConstMeta =>
      const TaskConstMeta(debugName: "enable_recovery", argNames: []);

  @override
  Future<String> crateApiMatrixEnsureRecoveryFor({required String role}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixEnsureRecoveryForConstMeta,
        argValues: [role],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixEnsureRecoveryForConstMeta =>
      const TaskConstMeta(debugName: "ensure_recovery_for", argNames: ["role"]);

  @override
  Future<String?> crateApiMatrixFetchEventContent({
    required String role,
    required String roomId,
    required String eventId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixFetchEventContentConstMeta,
        argValues: [role, roomId, eventId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixFetchEventContentConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_event_content",
        argNames: ["role", "roomId", "eventId"],
      );

  @override
  Future<String?> crateApiMatrixGetDisplayName({required String role}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetDisplayNameConstMeta,
        argValues: [role],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetDisplayNameConstMeta =>
      const TaskConstMeta(debugName: "get_display_name", argNames: ["role"]);

  @override
  Future<String> crateApiMatrixGetOrCreatePinDm({required String pinUid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pinUid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetOrCreatePinDmConstMeta,
        argValues: [pinUid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetOrCreatePinDmConstMeta =>
      const TaskConstMeta(
        debugName: "get_or_create_pin_dm",
        argNames: ["pinUid"],
      );

  @override
  Future<String?> crateApiMatrixGetPrefsState({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetPrefsStateConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetPrefsStateConstMeta =>
      const TaskConstMeta(debugName: "get_prefs_state", argNames: ["roomId"]);

  @override
  Future<String?> crateApiMatrixGetState({
    required String role,
    required String roomId,
    required String eventType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixGetStateConstMeta,
        argValues: [role, roomId, eventType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixGetStateConstMeta => const TaskConstMeta(
    debugName: "get_state",
    argNames: ["role", "roomId", "eventType"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiMatrixIsLoggedIn() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixIsLoggedInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixIsLoggedInConstMeta =>
      const TaskConstMeta(debugName: "is_logged_in", argNames: []);

  @override
  Future<void> crateApiMatrixJoinRoom({
    required String role,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixJoinRoomConstMeta,
        argValues: [role, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixJoinRoomConstMeta =>
      const TaskConstMeta(debugName: "join_room", argNames: ["role", "roomId"]);

  @override
  Future<void> crateApiMatrixLeaveRoom({
    required String role,
    required String roomId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixLeaveRoomConstMeta,
        argValues: [role, roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLeaveRoomConstMeta => const TaskConstMeta(
    debugName: "leave_room",
    argNames: ["role", "roomId"],
  );

  @override
  Future<List<RoomSummary>> crateApiMatrixListRooms() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_room_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixListRoomsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixListRoomsConstMeta =>
      const TaskConstMeta(debugName: "list_rooms", argNames: []);

  @override
  Future<Session> crateApiMatrixLogin({
    required String role,
    required String homeserver,
    required String dbPath,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixLoginConstMeta,
        argValues: [role, homeserver, dbPath, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLoginConstMeta => const TaskConstMeta(
    debugName: "login",
    argNames: ["role", "homeserver", "dbPath", "username", "password"],
  );

  @override
  Future<Session> crateApiMatrixLoginToken({
    required String role,
    required String homeserver,
    required String dbPath,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixLoginTokenConstMeta,
        argValues: [role, homeserver, dbPath, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLoginTokenConstMeta => const TaskConstMeta(
    debugName: "login_token",
    argNames: ["role", "homeserver", "dbPath", "token"],
  );

  @override
  Future<void> crateApiMatrixLogout({
    required String role,
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixLogoutConstMeta,
        argValues: [role, dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: ["role", "dbPath"]);

  @override
  Future<void> crateApiMatrixRecoverWithKey({required String recoveryKey}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recoveryKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRecoverWithKeyConstMeta,
        argValues: [recoveryKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRecoverWithKeyConstMeta =>
      const TaskConstMeta(
        debugName: "recover_with_key",
        argNames: ["recoveryKey"],
      );

  @override
  Future<void> crateApiMatrixRecoverWithKeyFor({
    required String role,
    required String recoveryKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(recoveryKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRecoverWithKeyForConstMeta,
        argValues: [role, recoveryKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRecoverWithKeyForConstMeta =>
      const TaskConstMeta(
        debugName: "recover_with_key_for",
        argNames: ["role", "recoveryKey"],
      );

  @override
  Future<String> crateApiMatrixRecoveryState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRecoveryStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRecoveryStateConstMeta =>
      const TaskConstMeta(debugName: "recovery_state", argNames: []);

  @override
  Future<String> crateApiMatrixResetRecovery({required String password}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixResetRecoveryConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixResetRecoveryConstMeta =>
      const TaskConstMeta(debugName: "reset_recovery", argNames: ["password"]);

  @override
  Future<String> crateApiMatrixResetRecoveryKey() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixResetRecoveryKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixResetRecoveryKeyConstMeta =>
      const TaskConstMeta(debugName: "reset_recovery_key", argNames: []);

  @override
  Future<void> crateApiMatrixRestore({
    required String role,
    required String homeserver,
    required String dbPath,
    required String userId,
    required String deviceId,
    required String accessToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(userId, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(accessToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRestoreConstMeta,
        argValues: [role, homeserver, dbPath, userId, deviceId, accessToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRestoreConstMeta => const TaskConstMeta(
    debugName: "restore",
    argNames: [
      "role",
      "homeserver",
      "dbPath",
      "userId",
      "deviceId",
      "accessToken",
    ],
  );

  @override
  Future<bool> crateApiMatrixRoomInStore({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixRoomInStoreConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRoomInStoreConstMeta =>
      const TaskConstMeta(debugName: "room_in_store", argNames: ["roomId"]);

  @override
  Future<List<String>> crateApiMatrixRoomMembers({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRoomMembersConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRoomMembersConstMeta =>
      const TaskConstMeta(debugName: "room_members", argNames: ["roomId"]);

  @override
  Future<TimelinePage> crateApiMatrixRoomMessages({
    required String role,
    required String roomId,
    String? from,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          sse_encode_opt_String(from, serializer);
          sse_encode_u_16(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_timeline_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixRoomMessagesConstMeta,
        argValues: [role, roomId, from, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixRoomMessagesConstMeta => const TaskConstMeta(
    debugName: "room_messages",
    argNames: ["role", "roomId", "from", "limit"],
  );

  @override
  Future<String?> crateApiMatrixSecretGet({
    required String role,
    required String recoveryKey,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(recoveryKey, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSecretGetConstMeta,
        argValues: [role, recoveryKey, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSecretGetConstMeta => const TaskConstMeta(
    debugName: "secret_get",
    argNames: ["role", "recoveryKey", "name"],
  );

  @override
  Future<void> crateApiMatrixSecretPut({
    required String role,
    required String recoveryKey,
    required String name,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(recoveryKey, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSecretPutConstMeta,
        argValues: [role, recoveryKey, name, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSecretPutConstMeta => const TaskConstMeta(
    debugName: "secret_put",
    argNames: ["role", "recoveryKey", "name", "value"],
  );

  @override
  Future<String> crateApiMatrixSendAttachment({
    required String role,
    required String roomId,
    required String filename,
    required String mime,
    required List<int> bytes,
    String? caption,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          sse_encode_String(filename, serializer);
          sse_encode_String(mime, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_opt_String(caption, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSendAttachmentConstMeta,
        argValues: [role, roomId, filename, mime, bytes, caption],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendAttachmentConstMeta =>
      const TaskConstMeta(
        debugName: "send_attachment",
        argNames: ["role", "roomId", "filename", "mime", "bytes", "caption"],
      );

  @override
  Future<String> crateApiMatrixSendCustomEvent({
    required String role,
    required String roomId,
    required String eventType,
    required String contentJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_String(contentJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSendCustomEventConstMeta,
        argValues: [role, roomId, eventType, contentJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendCustomEventConstMeta =>
      const TaskConstMeta(
        debugName: "send_custom_event",
        argNames: ["role", "roomId", "eventType", "contentJson"],
      );

  @override
  Future<String> crateApiMatrixSendText({
    required String role,
    required String roomId,
    required String body,
    String? flexJson,
    String? metaJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          sse_encode_String(body, serializer);
          sse_encode_opt_String(flexJson, serializer);
          sse_encode_opt_String(metaJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSendTextConstMeta,
        argValues: [role, roomId, body, flexJson, metaJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSendTextConstMeta => const TaskConstMeta(
    debugName: "send_text",
    argNames: ["role", "roomId", "body", "flexJson", "metaJson"],
  );

  @override
  Future<void> crateApiMatrixSetDisplayName({
    required String role,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSetDisplayNameConstMeta,
        argValues: [role, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSetDisplayNameConstMeta =>
      const TaskConstMeta(
        debugName: "set_display_name",
        argNames: ["role", "name"],
      );

  @override
  Future<void> crateApiMatrixSetState({
    required String role,
    required String roomId,
    required String eventType,
    required String contentJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          sse_encode_String(roomId, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_String(contentJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSetStateConstMeta,
        argValues: [role, roomId, eventType, contentJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSetStateConstMeta => const TaskConstMeta(
    debugName: "set_state",
    argNames: ["role", "roomId", "eventType", "contentJson"],
  );

  @override
  Future<String> crateApiMatrixSsoLoginUrl({
    required String homeserver,
    required String dbPath,
    required String redirectUrl,
    String? idpId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(redirectUrl, serializer);
          sse_encode_opt_String(idpId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixSsoLoginUrlConstMeta,
        argValues: [homeserver, dbPath, redirectUrl, idpId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixSsoLoginUrlConstMeta => const TaskConstMeta(
    debugName: "sso_login_url",
    argNames: ["homeserver", "dbPath", "redirectUrl", "idpId"],
  );

  @override
  Stream<String> crateApiMatrixTraceStartMatrixTrace() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 43,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiMatrixTraceStartMatrixTraceConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMatrixTraceStartMatrixTraceConstMeta =>
      const TaskConstMeta(debugName: "start_matrix_trace", argNames: ["sink"]);

  @override
  Stream<ChatMessage> crateApiMatrixStartSync() {
    final sink = RustStreamSink<ChatMessage>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_chat_message_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 44,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiMatrixStartSyncConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMatrixStartSyncConstMeta =>
      const TaskConstMeta(debugName: "start_sync", argNames: ["sink"]);

  @override
  Future<void> crateApiMatrixStartSyncRole({required String role}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(role, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixStartSyncRoleConstMeta,
        argValues: [role],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixStartSyncRoleConstMeta =>
      const TaskConstMeta(debugName: "start_sync_role", argNames: ["role"]);

  @override
  Future<void> crateApiMatrixVerificationAccept({required String flowId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(flowId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixVerificationAcceptConstMeta,
        argValues: [flowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixVerificationAcceptConstMeta =>
      const TaskConstMeta(
        debugName: "verification_accept",
        argNames: ["flowId"],
      );

  @override
  Future<void> crateApiMatrixVerificationCancel({required String flowId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(flowId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixVerificationCancelConstMeta,
        argValues: [flowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixVerificationCancelConstMeta =>
      const TaskConstMeta(
        debugName: "verification_cancel",
        argNames: ["flowId"],
      );

  @override
  Future<void> crateApiMatrixVerificationConfirm({required String flowId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(flowId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixVerificationConfirmConstMeta,
        argValues: [flowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixVerificationConfirmConstMeta =>
      const TaskConstMeta(
        debugName: "verification_confirm",
        argNames: ["flowId"],
      );

  @override
  Future<IncomingVerification?> crateApiMatrixVerificationPollIncoming() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_incoming_verification,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMatrixVerificationPollIncomingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixVerificationPollIncomingConstMeta =>
      const TaskConstMeta(
        debugName: "verification_poll_incoming",
        argNames: [],
      );

  @override
  Future<String> crateApiMatrixVerificationRequestSelf() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixVerificationRequestSelfConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixVerificationRequestSelfConstMeta =>
      const TaskConstMeta(debugName: "verification_request_self", argNames: []);

  @override
  Future<VerificationTick> crateApiMatrixVerificationTick({
    required String flowId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(flowId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_verification_tick,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMatrixVerificationTickConstMeta,
        argValues: [flowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMatrixVerificationTickConstMeta =>
      const TaskConstMeta(debugName: "verification_tick", argNames: ["flowId"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ChatMessage> dco_decode_StreamSink_chat_message_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  IncomingVerification dco_decode_box_autoadd_incoming_verification(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_incoming_verification(raw);
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return ChatMessage(
      roomId: dco_decode_String(arr[0]),
      eventId: dco_decode_String(arr[1]),
      sender: dco_decode_String(arr[2]),
      body: dco_decode_String(arr[3]),
      timestampMs: dco_decode_u_64(arr[4]),
      isMe: dco_decode_bool(arr[5]),
      kind: dco_decode_String(arr[6]),
      replyToEventId: dco_decode_opt_String(arr[7]),
      reactionTarget: dco_decode_opt_String(arr[8]),
      reactionKey: dco_decode_opt_String(arr[9]),
      mediaUrl: dco_decode_opt_String(arr[10]),
      mediaMime: dco_decode_opt_String(arr[11]),
      flexJson: dco_decode_opt_String(arr[12]),
      metaJson: dco_decode_opt_String(arr[13]),
      recvRole: dco_decode_String(arr[14]),
    );
  }

  @protected
  E2eeStatus dco_decode_e_2_ee_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return E2eeStatus(
      userId: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      recovery: dco_decode_String(arr[2]),
      crossSigningReady: dco_decode_bool(arr[3]),
      deviceVerified: dco_decode_bool(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  IncomingVerification dco_decode_incoming_verification(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return IncomingVerification(
      sender: dco_decode_String(arr[0]),
      flowId: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RoomSummary> dco_decode_list_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_room_summary).toList();
  }

  @protected
  List<SasEmoji> dco_decode_list_sas_emoji(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sas_emoji).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  IncomingVerification? dco_decode_opt_box_autoadd_incoming_verification(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_incoming_verification(raw);
  }

  @protected
  List<SasEmoji>? dco_decode_opt_list_sas_emoji(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_sas_emoji(raw);
  }

  @protected
  RoomSummary dco_decode_room_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RoomSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      isEncrypted: dco_decode_bool(arr[2]),
    );
  }

  @protected
  SasEmoji dco_decode_sas_emoji(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SasEmoji(
      symbol: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
    );
  }

  @protected
  Session dco_decode_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Session(
      homeserver: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      deviceId: dco_decode_String(arr[2]),
      accessToken: dco_decode_String(arr[3]),
    );
  }

  @protected
  TimelinePage dco_decode_timeline_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TimelinePage(
      endToken: dco_decode_opt_String(arr[0]),
      messages: dco_decode_list_chat_message(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VerificationTick dco_decode_verification_tick(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VerificationTick(
      state: dco_decode_String(arr[0]),
      emoji: dco_decode_opt_list_sas_emoji(arr[1]),
      done: dco_decode_bool(arr[2]),
      cancelled: dco_decode_bool(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ChatMessage> sse_decode_StreamSink_chat_message_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  IncomingVerification sse_decode_box_autoadd_incoming_verification(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_incoming_verification(deserializer));
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomId = sse_decode_String(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    var var_sender = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_isMe = sse_decode_bool(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_replyToEventId = sse_decode_opt_String(deserializer);
    var var_reactionTarget = sse_decode_opt_String(deserializer);
    var var_reactionKey = sse_decode_opt_String(deserializer);
    var var_mediaUrl = sse_decode_opt_String(deserializer);
    var var_mediaMime = sse_decode_opt_String(deserializer);
    var var_flexJson = sse_decode_opt_String(deserializer);
    var var_metaJson = sse_decode_opt_String(deserializer);
    var var_recvRole = sse_decode_String(deserializer);
    return ChatMessage(
      roomId: var_roomId,
      eventId: var_eventId,
      sender: var_sender,
      body: var_body,
      timestampMs: var_timestampMs,
      isMe: var_isMe,
      kind: var_kind,
      replyToEventId: var_replyToEventId,
      reactionTarget: var_reactionTarget,
      reactionKey: var_reactionKey,
      mediaUrl: var_mediaUrl,
      mediaMime: var_mediaMime,
      flexJson: var_flexJson,
      metaJson: var_metaJson,
      recvRole: var_recvRole,
    );
  }

  @protected
  E2eeStatus sse_decode_e_2_ee_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_recovery = sse_decode_String(deserializer);
    var var_crossSigningReady = sse_decode_bool(deserializer);
    var var_deviceVerified = sse_decode_bool(deserializer);
    return E2eeStatus(
      userId: var_userId,
      deviceId: var_deviceId,
      recovery: var_recovery,
      crossSigningReady: var_crossSigningReady,
      deviceVerified: var_deviceVerified,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  IncomingVerification sse_decode_incoming_verification(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sender = sse_decode_String(deserializer);
    var var_flowId = sse_decode_String(deserializer);
    return IncomingVerification(sender: var_sender, flowId: var_flowId);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RoomSummary> sse_decode_list_room_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RoomSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_room_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<SasEmoji> sse_decode_list_sas_emoji(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SasEmoji>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sas_emoji(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  IncomingVerification? sse_decode_opt_box_autoadd_incoming_verification(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_incoming_verification(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<SasEmoji>? sse_decode_opt_list_sas_emoji(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_sas_emoji(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RoomSummary sse_decode_room_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    return RoomSummary(
      id: var_id,
      name: var_name,
      isEncrypted: var_isEncrypted,
    );
  }

  @protected
  SasEmoji sse_decode_sas_emoji(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_symbol = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return SasEmoji(symbol: var_symbol, description: var_description);
  }

  @protected
  Session sse_decode_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_homeserver = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    return Session(
      homeserver: var_homeserver,
      userId: var_userId,
      deviceId: var_deviceId,
      accessToken: var_accessToken,
    );
  }

  @protected
  TimelinePage sse_decode_timeline_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_endToken = sse_decode_opt_String(deserializer);
    var var_messages = sse_decode_list_chat_message(deserializer);
    return TimelinePage(endToken: var_endToken, messages: var_messages);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VerificationTick sse_decode_verification_tick(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_String(deserializer);
    var var_emoji = sse_decode_opt_list_sas_emoji(deserializer);
    var var_done = sse_decode_bool(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    return VerificationTick(
      state: var_state,
      emoji: var_emoji,
      done: var_done,
      cancelled: var_cancelled,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_chat_message_Sse(
    RustStreamSink<ChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_incoming_verification(
    IncomingVerification self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_incoming_verification(self, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.eventId, serializer);
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_bool(self.isMe, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.replyToEventId, serializer);
    sse_encode_opt_String(self.reactionTarget, serializer);
    sse_encode_opt_String(self.reactionKey, serializer);
    sse_encode_opt_String(self.mediaUrl, serializer);
    sse_encode_opt_String(self.mediaMime, serializer);
    sse_encode_opt_String(self.flexJson, serializer);
    sse_encode_opt_String(self.metaJson, serializer);
    sse_encode_String(self.recvRole, serializer);
  }

  @protected
  void sse_encode_e_2_ee_status(E2eeStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.recovery, serializer);
    sse_encode_bool(self.crossSigningReady, serializer);
    sse_encode_bool(self.deviceVerified, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_incoming_verification(
    IncomingVerification self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.flowId, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_room_summary(
    List<RoomSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_room_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sas_emoji(
    List<SasEmoji> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sas_emoji(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_incoming_verification(
    IncomingVerification? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_incoming_verification(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_sas_emoji(
    List<SasEmoji>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_sas_emoji(self, serializer);
    }
  }

  @protected
  void sse_encode_room_summary(RoomSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
  }

  @protected
  void sse_encode_sas_emoji(SasEmoji self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.symbol, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_session(Session self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.homeserver, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.accessToken, serializer);
  }

  @protected
  void sse_encode_timeline_page(TimelinePage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.endToken, serializer);
    sse_encode_list_chat_message(self.messages, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verification_tick(
    VerificationTick self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.state, serializer);
    sse_encode_opt_list_sas_emoji(self.emoji, serializer);
    sse_encode_bool(self.done, serializer);
    sse_encode_bool(self.cancelled, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
