// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Embedder`

/// Load the ONNX model + tokenizer from in-memory bytes. Idempotent: a second
/// call with an embedder already loaded is a no-op (returns Ok). [model] is the
/// `.onnx` file bytes; [tokenizer_json] is the `tokenizer.json` text.
Future<void> embedInit({
  required List<int> model,
  required String tokenizerJson,
}) => RustLib.instance.api.crateApiEmbedEmbedInit(
  model: model,
  tokenizerJson: tokenizerJson,
);

/// True once a model is loaded — lets Dart skip embedding (recency fallback)
/// until the model is provisioned.
bool embedReady() => RustLib.instance.api.crateApiEmbedEmbedReady();

/// Embed one string → a mean-pooled, L2-normalized vector. The caller adds any
/// model-specific prefix (e5 wants "query: " / "passage: ") before calling.
/// Errors if [embed_init] hasn't run.
Future<Float32List> embedText({required String text}) =>
    RustLib.instance.api.crateApiEmbedEmbedText(text: text);
