// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `body_for_log`, `emit_log`, `error_line`, `plain_response`, `proxy_request`

/// Start (or re-attach) the in-process inspector proxy. Binds `127.0.0.1:0`,
/// spawns an accept loop on the matrix runtime, stores the sink + port, and
/// returns the assigned port. Idempotent: if a port is already bound, this just
/// replaces the sink and returns that port (the existing accept loop keeps
/// serving). DEBUG-only — calling this is what makes `build_client` route
/// matrix-sdk through the proxy.
Stream<String> startMatrixInspector() =>
    RustLib.instance.api.crateApiInspectorStartMatrixInspector();
