// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FieldVisitor`, `HttpCall`, `HttpLayer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_close`, `on_new_span`, `on_record`, `record_debug`, `record_i64`, `record_str`, `record_u64`

/// Begin passive capture of matrix-sdk HTTP metadata, streaming one JSON line
/// per request to Dart. Safe to call multiple times: the sink is replaced and
/// the global subscriber is installed at most once. Never errors hard — if the
/// subscriber can't be installed (some other global subscriber is already set)
/// capture simply won't happen and `Ok(())` is still returned.
Stream<String> startMatrixTrace() =>
    RustLib.instance.api.crateApiMatrixTraceStartMatrixTrace();
