// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block`, `build_client`, `client_for`, `current_client`, `emit`, `map_timeline_to_chat`, `register_handlers`, `room_by_id_role`, `room_by_id`, `source_url`, `spawn_sync_loop`, `stop_sync`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

/// Whether `room_id` is present in the user client's local store (no network).
/// A cached room id from a previous account isn't in this client → every room
/// read ("room not found") fails; callers use this to drop a stale cache and
/// re-resolve. Also false for a valid room not yet synced into a fresh store.
Future<bool> roomInStore({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixRoomInStore(roomId: roomId);

/// Password login against `homeserver`, persisting crypto + state at `db_path`.
/// Returns the session so Dart can store it in the Keychain/Keystore.
Future<Session> login({
  required String role,
  required String homeserver,
  required String dbPath,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiMatrixLogin(
  role: role,
  homeserver: homeserver,
  dbPath: dbPath,
  username: username,
  password: password,
);

/// Restore a previously stored session (no network login). Verifies nothing —
/// the first sync will surface an invalid token.
Future<void> restore({
  required String role,
  required String homeserver,
  required String dbPath,
  required String userId,
  required String deviceId,
  required String accessToken,
}) => RustLib.instance.api.crateApiMatrixRestore(
  role: role,
  homeserver: homeserver,
  dbPath: dbPath,
  userId: userId,
  deviceId: deviceId,
  accessToken: accessToken,
);

/// One foreground sync, then the list of joined rooms.
Future<List<RoomSummary>> listRooms() =>
    RustLib.instance.api.crateApiMatrixListRooms();

/// Read persona prefs back from room state. Returns the `content` JSON string,
/// or None if never set. Used on startup to rehydrate prefs after a reinstall.
Future<String?> getPrefsState({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetPrefsState(roomId: roomId);

/// Read an arbitrary room STATE event's content JSON (e.g. `io.tokens2.facts` /
/// `.knowledge`) from the `role` client, or None if never set. Generic sibling
/// of [`get_prefs_state`] for cross-device memory sync.
Future<String?> getState({
  required String role,
  required String roomId,
  required String eventType,
}) => RustLib.instance.api.crateApiMatrixGetState(
  role: role,
  roomId: roomId,
  eventType: eventType,
);

/// Begin a continuous background sync for the USER client, streaming each
/// decrypted message to Dart. Sets the shared sink. Call once after login/restore.
Stream<ChatMessage> startSync() =>
    RustLib.instance.api.crateApiMatrixStartSync();

/// Begin a continuous background sync for a non-default role (e.g. "pin"),
/// reusing the shared sink already set by [`start_sync`]. Events from this
/// client flow into the same Dart stream tagged with `recv_role`.
Future<void> startSyncRole({required String role}) =>
    RustLib.instance.api.crateApiMatrixStartSyncRole(role: role);

/// Post an `m.room.message` to `room_id` from the `role` client, carrying the
/// custom `io.tokens2.flex` / `io.tokens2.meta` keys (so flex cards + used/hint
/// survive). `text_plain()` would drop unknown keys, so we send raw content.
/// Returns the new event id.
Future<String> sendText({
  required String role,
  required String roomId,
  required String body,
  String? flexJson,
  String? metaJson,
}) => RustLib.instance.api.crateApiMatrixSendText(
  role: role,
  roomId: roomId,
  body: body,
  flexJson: flexJson,
  metaJson: metaJson,
);

/// Send an arbitrary E2EE timeline event (`event_type` ≠ m.room.message) with
/// `content_json` as the content. matrix-sdk encrypts it in an E2EE room. It does
/// NOT render in the chat list (which filters to m.room.message). Used to store
/// private data (e.g. the agent's memory) encrypted — the homeserver can't read
/// it, unlike a plaintext state event. Returns the event id (store it in a
/// plaintext state-event pointer so it can be fetched back reliably).
Future<String> sendCustomEvent({
  required String role,
  required String roomId,
  required String eventType,
  required String contentJson,
}) => RustLib.instance.api.crateApiMatrixSendCustomEvent(
  role: role,
  roomId: roomId,
  eventType: eventType,
  contentJson: contentJson,
);

/// Fetch + decrypt a single timeline event by id, returning its `content` as a
/// JSON string (None if absent). Pairs with [`send_custom_event`]: read the
/// event id from a state-event pointer, then fetch the encrypted content here.
Future<String?> fetchEventContent({
  required String role,
  required String roomId,
  required String eventId,
}) => RustLib.instance.api.crateApiMatrixFetchEventContent(
  role: role,
  roomId: roomId,
  eventId: eventId,
);

/// Upload `bytes` as an attachment to `room_id` from the `role` client. In an
/// E2EE room matrix-sdk encrypts the upload automatically. Returns the event id.
Future<String> sendAttachment({
  required String role,
  required String roomId,
  required String filename,
  required String mime,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiMatrixSendAttachment(
  role: role,
  roomId: roomId,
  filename: filename,
  mime: mime,
  bytes: bytes,
);

/// Paginate `room_id` backward (newest→oldest) from the `role` client. Pass the
/// previous page's `end_token` as `from` to continue older. Returns mapped
/// message events; `messages` is in server (backward) order — Dart reverses.
Future<TimelinePage> roomMessages({
  required String role,
  required String roomId,
  String? from,
  required int limit,
}) => RustLib.instance.api.crateApiMatrixRoomMessages(
  role: role,
  roomId: roomId,
  from: from,
  limit: limit,
);

/// Whether a key backup exists on the homeserver for the user account. A fresh
/// device must RESTORE (not create) when true — creating would delete the
/// existing backup and lock other devices out. Hits the server (authoritative,
/// unlike the local recovery state which is empty before first sync).
Future<bool> backupExistsOnServer() =>
    RustLib.instance.api.crateApiMatrixBackupExistsOnServer();

/// Set the Matrix profile display name for the `role` client's account. The
/// localpart stays a hash (doesn't leak the email in the user_id); the
/// displayname makes the account identifiable in the admin UI.
Future<void> setDisplayName({required String role, required String name}) =>
    RustLib.instance.api.crateApiMatrixSetDisplayName(role: role, name: name);

/// Read the Matrix profile display name for `role`'s account (we set it to the
/// email), or None. Lets a token-restored session still recover the email.
Future<String?> getDisplayName({required String role}) =>
    RustLib.instance.api.crateApiMatrixGetDisplayName(role: role);

/// Get-or-create the encrypted DM between the user account and the ปิ่น account.
/// Acts on the USER client; `create_dm` auto-enables E2EE + invites pin. Returns
/// the room id. The pin client must accept the invite via its own sync.
Future<String> getOrCreatePinDm({required String pinUid}) =>
    RustLib.instance.api.crateApiMatrixGetOrCreatePinDm(pinUid: pinUid);

/// Accept a pending invite to `room_id` on the `role` client (the pin client
/// joins the DM the user created).
Future<void> joinRoom({required String role, required String roomId}) =>
    RustLib.instance.api.crateApiMatrixJoinRoom(role: role, roomId: roomId);

/// Write a room STATE event (e.g. `io.tokens2.prefs` / `.facts` / `.knowledge`)
/// from the `role` client, so persona/memory sync cross-device. Mirrors
/// [`get_prefs_state`].
Future<void> setState({
  required String role,
  required String roomId,
  required String eventType,
  required String contentJson,
}) => RustLib.instance.api.crateApiMatrixSetState(
  role: role,
  roomId: roomId,
  eventType: eventType,
  contentJson: contentJson,
);

/// Download (and decrypt, if E2EE) the media attached to a message event, write
/// it to a temp file, and return that path. Used to render images inline.
Future<String> downloadMedia({
  required String roomId,
  required String eventId,
}) => RustLib.instance.api.crateApiMatrixDownloadMedia(
  roomId: roomId,
  eventId: eventId,
);

/// Joined members of a room (user ids) — for the Settings debug section.
Future<List<String>> roomMembers({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixRoomMembers(roomId: roomId);

/// E2EE diagnostics for the Settings debug section.
Future<E2eeStatus> e2EeStatus() =>
    RustLib.instance.api.crateApiMatrixE2EeStatus();

/// Whether key backup/recovery is already set up on the server for this account:
/// "enabled" (a recovery key exists → returning user should RESTORE),
/// "disabled" (first time → CREATE), "incomplete", or "unknown".
Future<String> recoveryState() =>
    RustLib.instance.api.crateApiMatrixRecoveryState();

Future<String> enableRecovery() =>
    RustLib.instance.api.crateApiMatrixEnableRecovery();

/// Start fresh when the user lost their recovery key: delete the stale backup
/// on the server, then create a new backup + recovery key.
///
/// We can't use `recovery().disable()` here: when the device holds no usable
/// local backup key (the lost-key case), `backups().disable()` returns
/// "backups are not enabled" and never reaches the server-side delete. And
/// `enable()` on its own returns `BackupExistsOnServer` because the old backup
/// is still there. So we delete the server backup version directly over the CS
/// API (no local key needed), which lets `enable()` create a fresh one. Does
/// not touch cross-signing, so no UIA/password is needed.
Future<String> resetRecoveryKey() =>
    RustLib.instance.api.crateApiMatrixResetRecoveryKey();

/// Fully (re)bootstrap E2EE: set up cross-signing (needs the account password
/// for UIA) + key backup + recovery, and return the new recovery key. Fixes a
/// "cross-signing: not ready / recovery: incomplete" state.
Future<String> resetRecovery({required String password}) =>
    RustLib.instance.api.crateApiMatrixResetRecovery(password: password);

/// Restore E2EE keys on this device using a previously saved recovery key.
Future<void> recoverWithKey({required String recoveryKey}) =>
    RustLib.instance.api.crateApiMatrixRecoverWithKey(recoveryKey: recoveryKey);

/// Enable (or reset) key backup + recovery for `role`'s account and return the
/// new recovery key. Deletes any stale server backup first (idempotent across
/// re-runs / lost-key state), then enables. Role-aware sibling of
/// [`reset_recovery_key`] — used to set up recovery on BOTH the user and ปิ่น
/// accounts so one QR can carry both keys.
Future<String> ensureRecoveryFor({required String role}) =>
    RustLib.instance.api.crateApiMatrixEnsureRecoveryFor(role: role);

Future<void> recoverWithKeyFor({
  required String role,
  required String recoveryKey,
}) => RustLib.instance.api.crateApiMatrixRecoverWithKeyFor(
  role: role,
  recoveryKey: recoveryKey,
);

/// Log out a single role's session ("user" | "pin") and wipe its store. Dart
/// calls this once per role on full logout.
Future<void> logout({required String role, required String dbPath}) =>
    RustLib.instance.api.crateApiMatrixLogout(role: role, dbPath: dbPath);

bool isLoggedIn() => RustLib.instance.api.crateApiMatrixIsLoggedIn();

class ChatMessage {
  final String roomId;
  final String eventId;
  final String sender;
  final String body;
  final BigInt timestampMs;
  final bool isMe;

  /// "text" | "image" | "file" | "audio" | "video" | "reaction"
  final String kind;

  /// Event id this message replies to (m.in_reply_to), if any.
  final String? replyToEventId;

  /// For kind == "reaction": the event being reacted to.
  final String? reactionTarget;

  /// For kind == "reaction": the emoji/key.
  final String? reactionKey;

  /// For media kinds: the mxc:// URL (download handled separately).
  final String? mediaUrl;
  final String? mediaMime;

  /// Raw JSON of the `io.tokens2.flex` card, if this message carries one.
  final String? flexJson;

  /// Raw JSON of the `io.tokens2.meta` content key (assistant used/hint), if any.
  final String? metaJson;

  /// Role of the client that RECEIVED this event ("user" | "pin"). Dart maps
  /// the event's `sender` against the known user/pin ids to decide the bubble
  /// side; this just says which session's sync surfaced it.
  final String recvRole;

  const ChatMessage({
    required this.roomId,
    required this.eventId,
    required this.sender,
    required this.body,
    required this.timestampMs,
    required this.isMe,
    required this.kind,
    this.replyToEventId,
    this.reactionTarget,
    this.reactionKey,
    this.mediaUrl,
    this.mediaMime,
    this.flexJson,
    this.metaJson,
    required this.recvRole,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      eventId.hashCode ^
      sender.hashCode ^
      body.hashCode ^
      timestampMs.hashCode ^
      isMe.hashCode ^
      kind.hashCode ^
      replyToEventId.hashCode ^
      reactionTarget.hashCode ^
      reactionKey.hashCode ^
      mediaUrl.hashCode ^
      mediaMime.hashCode ^
      flexJson.hashCode ^
      metaJson.hashCode ^
      recvRole.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          eventId == other.eventId &&
          sender == other.sender &&
          body == other.body &&
          timestampMs == other.timestampMs &&
          isMe == other.isMe &&
          kind == other.kind &&
          replyToEventId == other.replyToEventId &&
          reactionTarget == other.reactionTarget &&
          reactionKey == other.reactionKey &&
          mediaUrl == other.mediaUrl &&
          mediaMime == other.mediaMime &&
          flexJson == other.flexJson &&
          metaJson == other.metaJson &&
          recvRole == other.recvRole;
}

/// Enable E2EE key backup + cross-signing + recovery, returning the recovery
/// key for the user to save. With this, a fresh device can restore keys (fixes
/// "can't decrypt on new login"). Called during onboarding.
class E2eeStatus {
  final String userId;
  final String deviceId;
  final String recovery;
  final bool crossSigningReady;
  final bool deviceVerified;

  const E2eeStatus({
    required this.userId,
    required this.deviceId,
    required this.recovery,
    required this.crossSigningReady,
    required this.deviceVerified,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      deviceId.hashCode ^
      recovery.hashCode ^
      crossSigningReady.hashCode ^
      deviceVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is E2eeStatus &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          recovery == other.recovery &&
          crossSigningReady == other.crossSigningReady &&
          deviceVerified == other.deviceVerified;
}

class RoomSummary {
  final String id;
  final String name;
  final bool isEncrypted;

  const RoomSummary({
    required this.id,
    required this.name,
    required this.isEncrypted,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isEncrypted == other.isEncrypted;
}

class Session {
  final String homeserver;
  final String userId;
  final String deviceId;
  final String accessToken;

  const Session({
    required this.homeserver,
    required this.userId,
    required this.deviceId,
    required this.accessToken,
  });

  @override
  int get hashCode =>
      homeserver.hashCode ^
      userId.hashCode ^
      deviceId.hashCode ^
      accessToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Session &&
          runtimeType == other.runtimeType &&
          homeserver == other.homeserver &&
          userId == other.userId &&
          deviceId == other.deviceId &&
          accessToken == other.accessToken;
}

/// A page of decrypted timeline events, oldest→newest within the page.
class TimelinePage {
  /// Pagination token to pass as `from` on the next older page (None = start).
  final String? endToken;

  /// Mapped m.room.message events (non-message events are dropped).
  final List<ChatMessage> messages;

  const TimelinePage({this.endToken, required this.messages});

  @override
  int get hashCode => endToken.hashCode ^ messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelinePage &&
          runtimeType == other.runtimeType &&
          endToken == other.endToken &&
          messages == other.messages;
}
